theme: jekyll-theme-architect

title: Development of System Software Technologies Development of System Software Technologies

supervisor: Mitsuhisa Sato (RIKEN Center for Computational Science)

github:
  is_project_page: false
